version: "3.8"

services:
  database:
    image: postgres
    container_name: desafio-node06
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=fin_api
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: app-desafio
    restart: always
    ports:
      - 3232:3232
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database


volumes:
  pgdata:
    driver: local
