version: "3.8"

services:
  database:
    image: postgres
    container_name: desafio-node06
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=fin_api
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
    volumes:
      - pgdata:/user/postgres


volumes:
  pgdata:
    driver: local
